# Generated by Django 5.2 on 2025-05-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('welcome_text', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tech_tags', models.TextField(blank=True, help_text='Comma-separated values', null=True)),
                ('social_links', models.TextField(blank=True, help_text='JSON format: {"linkedin": "url", "github": "url", "twitter": "url", "email": "email"}', null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('availability_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Section',
            },
        ),
    ]
