# Generated by Django 5.2 on 2025-05-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_role', models.CharField(blank=True, help_text='e.g., Python Developer', max_length=100, null=True)),
                ('headline', models.CharField(blank=True, help_text='Main headline about yourself', max_length=150, null=True)),
                ('summary', models.TextField(blank=True, help_text='Detailed description about yourself', null=True)),
                ('skills_list', models.TextField(blank=True, help_text='Comma-separated skills (e.g., Web Development,Data Science,Machine Learning)', null=True)),
                ('pdf_resume', models.FileField(blank=True, help_text='Upload your resume in PDF format', null=True, upload_to='resumes/')),
                ('experience_years', models.IntegerField(blank=True, help_text='Years of professional experience', null=True)),
                ('project_count', models.IntegerField(blank=True, help_text='Number of completed projects', null=True)),
                ('education_summary', models.CharField(blank=True, help_text='e.g., BSc in Computer Science, University Name', max_length=250, null=True)),
                ('client_satisfaction', models.CharField(blank=True, help_text='e.g., 98%', max_length=10, null=True)),
                ('years_experience', models.CharField(blank=True, help_text='e.g., 5+', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
