# Generated by Django 5.2 on 2025-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='e.g., Tech Innovate Ltd.', max_length=150)),
                ('role', models.CharField(help_text='e.g., Software Developer', max_length=100)),
                ('start_year', models.IntegerField(help_text='Year when you started the job')),
                ('end_year', models.IntegerField(blank=True, help_text='Year when you ended the job (leave blank if current)', null=True)),
                ('description', models.TextField(help_text='Brief description of your role and responsibilities')),
                ('highlights', models.TextField(help_text='Comma-separated achievements/highlights (e.g., Built RESTful APIs, Improved performance by 25%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_year'],
            },
        ),
    ]
