# Generated by Django 5.2 on 2025-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=150)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('python', 'Python'), ('data', 'Data Science'), ('ml', 'Machine Learning'), ('nlp', 'Natural Language Processing'), ('api', 'API Development'), ('mobile', 'Mobile Development'), ('other', 'Other')], help_text='Project category for filtering', max_length=50)),
                ('image', models.ImageField(help_text='Project screenshot or preview image', upload_to='projects/')),
                ('short_description', models.TextField(help_text='Brief description of the project')),
                ('tech_stack', models.TextField(help_text='Comma-separated technologies (e.g., Django,PostgreSQL,Stripe,AWS)')),
                ('preview_url', models.URLField(blank=True, help_text='Live demo or preview URL', null=True)),
                ('code_url', models.URLField(blank=True, help_text='Source code URL (GitHub, GitLab, etc.)', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured project')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
