# Generated by Django 5.2 on 2025-05-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_certification_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Your location/address', max_length=255)),
                ('email', models.EmailField(help_text='Your contact email', max_length=254)),
                ('phone', models.CharField(help_text='Your phone number', max_length=20)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('github', models.URLField(blank=True, help_text='GitHub profile URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter profile URL', null=True)),
                ('stack_overflow', models.URLField(blank=True, help_text='Stack Overflow profile URL', null=True)),
                ('dribbble', models.URLField(blank=True, help_text='Dribbble profile URL', null=True)),
                ('additional_info', models.TextField(blank=True, help_text='Additional availability/contact information')),
                ('map_url', models.URLField(blank=True, help_text='Google Maps embed URL or location URL', null=True)),
                ('timezone', models.CharField(blank=True, help_text='Your timezone (e.g., GMT +6)', max_length=50)),
                ('availability_status', models.CharField(blank=True, help_text='Current availability status', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's name", max_length=100)),
                ('email', models.EmailField(help_text="Sender's email", max_length=254)),
                ('subject', models.CharField(help_text='Message subject', max_length=200)),
                ('message', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('python', 'Python'), ('data', 'Data Science'), ('ml', 'Machine Learning'), ('nlp', 'Natural Language Processing'), ('api', 'API Development'), ('mobile', 'Mobile Development'), ('other', 'Other')], help_text='Project category for filtering', max_length=50),
        ),
    ]
