# Generated by Django 5.2 on 2025-05-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contactinfo_contactmessage_alter_project_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_year', '-start_month'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month when you ended the job (leave blank if current)', null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='Month when you started the job'),
        ),
    ]
