# Generated by Django 5.2 on 2025-05-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_year'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_month',
        ),
    ]
