# Generated by Django 5.2 on 2025-05-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_education_options_education_end_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_year'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_year'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_month',
        ),
    ]
