# Generated by Django 5.2 on 2025-05-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_education_options_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.DateField(blank=True, help_text='Year when you ended the job (leave blank if current)', null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.DateField(help_text='Year when you started the job'),
        ),
    ]
